WebAppCalc/WebAppCalc/Models/CalcModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Threading.Tasks;
using BusinessLogicLayer;
using PagedList;

namespace WebAppCalc.Models
{
    public class CalcModel
    {
        [Required]
        [RegularExpression("^[0-9]*$",ErrorMessage="Number must be numeric")]
        [Range(1, 1000)]
        public int Calcvalue { get; set; }

        public IPagedList <string> result {get;set;}


    }


       
}

WebAppCalc/WebAppCalc/Controllers/CalcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppCalc.Models;
using BusinessLogicLayer;
using PagedList;

namespace WebAppCalc.Controllers
{
    public class CalcController : Controller
    {
        private readonly IFizzBuzzLogic FizzBuzzLogic;
        public CalcController(IFizzBuzzLogic FizzBuzzLogic)
        {
            this.FizzBuzzLogic = FizzBuzzLogic;
        }
        // GET: Calc
        public ActionResult Index()
        {
            return View();
        }

     
        public ActionResult Result(CalcModel calculator, int? page)
        {
            if (ModelState.IsValid)
            {
                int pageNumber = page != null ? Convert.ToInt32(page) : 1;
                int pageSize = 10;
                var fizzbuzzListDetails = this.FizzBuzzLogic.FizzBuzzDetails(calculator.Calcvalue);
                if (fizzbuzzListDetails != null)
                {
                    calculator.result = fizzbuzzListDetails.ToPagedList(pageNumber, pageSize);
                }
                
                
            }           
            return View("Index", calculator);
        }


    }
}

WebAppCalc/WebAppCalc/Views/Calc/Index.cshtml
@model WebAppCalc.Models.CalcModel
@using PagedList.Mvc

@{
    ViewBag.Title = "Calculation Project";
}


<h2>FizzBuzz Calculator</h2>


@using (Html.BeginForm("Result", "Calc", FormMethod.Get)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Calculation Model</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Enter a number between 1 to 1000", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calcvalue, new { htmlAttributes = new { type = "number",@class = "form-control" } })
               
                @Html.ValidationMessageFor(model => model.Calcvalue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
        @if (Model != null && Model.result != null)
        {
          <div class="row">
              <table class="table table-borderless">
                  @foreach (var item in Model.result)
                  {
                      <tr>
                          <td>
                              @{ 
                                  var result = item.Split(' ');
                                  if (result.Length > 1)
                                  {
                                      foreach (var val in result)
                                      {
                                          <span class="@val">@Html.Raw(@val)</span>
                                      }
                                  }
                                  else
                                  {
                                      <span class="@item">@Html.Raw(@item)</span>
                                  }
                              }
                          </td>
                      </tr>
                  }
              </table>
              <div class="pagination">
                  Page @(Model.result.PageCount < Model.result.PageNumber ? 0 : Model.result.PageNumber) of @Model.result.PageCount

                  @Html.PagedListPager(Model.result, page => Url.Action("Result", new { Calcvalue = Model.Calcvalue, page }))
              </div>
          </div>
        }
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppCalc/WebAppCalc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>